# Generated by Django 4.0.4 on 2022-05-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subject',
        ),
    ]
