# Generated by Django 4.0.4 on 2022-05-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
