# Generated by Django 4.0.2 on 2022-03-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_bids_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='price',
            new_name='starting_bid',
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='image_url',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
