# Generated by Django 4.0.2 on 2022-03-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_price_auctionlistings_starting_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='bids', to='auctions.AuctionListings'),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('hats', 'Hats'), ('jackets', 'Jackets')], max_length=100),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
