# Generated by Django 4.0.2 on 2022-03-24 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bids_listing_alter_auctionlistings_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='listing',
        ),
        migrations.AddField(
            model_name='bids',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionlistings'),
            preserve_default=False,
        ),
    ]
