# Generated by Django 4.0.2 on 2022-03-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_bids_listing_bids_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='highest_bid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
