# Generated by Django 4.0.2 on 2022-03-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlistings_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='highest_bid',
            field=models.IntegerField(null=True),
        ),
    ]
