# Generated by Django 4.0.2 on 2022-03-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_listings_user_watchlist_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='creator',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
