# Generated by Django 4.0.2 on 2022-03-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auctionlistings_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='won_listings',
            field=models.ManyToManyField(blank=True, related_name='winner', to='auctions.AuctionListings'),
        ),
    ]
