# Generated by Django 4.0.2 on 2022-03-27 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_user_won_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='won_listings',
        ),
        migrations.CreateModel(
            name='ClosedListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('starting_bid', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('image_url', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('shoes', 'Shoes'), ('hats', 'Hats'), ('jackets', 'Jackets')], max_length=100)),
                ('highest_bid', models.IntegerField(null=True)),
                ('creator', models.CharField(max_length=64)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
