# Generated by Django 4.0.2 on 2022-03-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_user_won_listings_closedlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='highest_bid_holder',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='closedlisting',
            name='highest_bid_holder',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
