# Generated by Django 4.0.2 on 2022-03-27 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auctionlistings_highest_bid_holder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedlisting',
            name='highest_bid_holder',
        ),
        migrations.AlterField(
            model_name='closedlisting',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
